### ISSUE TITLE
Size is show as zero and opennebula refuses to create an image

### ISSUE THREAD

**Issue by telmich** [OpenNebula-unmantained/addon-sheepdog#4]
Trying to import any image into the sheepdog store results in

Fri Feb 13 15:45:35 2015 [Z0][ReM][D]: Req:3872 UID:0 ImageAllocate invoked , "NAME="Ubuntu-14.04"...", 100
Fri Feb 13 15:45:36 2015 [Z0][ReM][E]: Req:3872 UID:0 ImageAllocate result FAILURE Not enough space in datastore

**Comment by telmich** [comment]
It seems that the dog is called without -a, which is required if the sheepdog cluster is not running on the frontend. Using

sudo $DOG node info -r -a "$HOST" | $AWK '{

may fix the problem at the moment.

Furethermore $DOG is setup to dog, but dog is in /usr/sbin, which is not in the PATH for oneadmin by default

**Comment by telmich** [comment]
Also it seems that sudo is not required at all (at least in my setup)

**Comment by telmich** [comment]
Testing

[15:57:18] entrance:~$ /usr/sbin/dog node info -a MYIP | awk '{    if ($1 == "Total") {

        print "TOTAL_MB=" int($2/1024/1024)
        print "USED_MB=" int($3/1024/1024)
        print "FREE_MB=" int($4/1024/1024)

    }
}'
TOTAL_MB=0
USED_MB=0
FREE_MB=0
TOTAL_MB=0
USED_MB=0
FREE_MB=0

**Comment by devfaz** [comment]
Did you setup your BRIDGE_LIST correctly?

**Comment by devfaz** [comment]
If you are *not* using your libvirt-Hosts as sheepdog-Hosts, you may also want to use

https://github.com/devfaz/one/commit/4b1e2e225b05dba69d3c149c5c6b55380133e5c7

as desc. in https://github.com/OpenNebula/addon-sheepdog/issues/1
